//
// Generated file, do not edit! Created by nedtool 5.6 from HelloMsg.msg.
//

#ifndef __HELLOMSG_M_H
#define __HELLOMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
  #include "Event.h"
// }}

/**
 * Class generated from <tt>HelloMsg.msg:6</tt> by nedtool.
 * <pre>
 * message HelloMsg
 * {
 *     name = "hello";
 *     kind = EventKind::HELLO;
 *     int id;
 *     int cid;
 *     int level;
 * }
 * </pre>
 */
class HelloMsg : public ::omnetpp::cMessage
{
  protected:
    int id;
    int cid;
    int level;

  private:
    void copy(const HelloMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HelloMsg&);

  public:
    HelloMsg(const char *name=nullptr, short kind=0);
    HelloMsg(const HelloMsg& other);
    virtual ~HelloMsg();
    HelloMsg& operator=(const HelloMsg& other);
    virtual HelloMsg *dup() const override {return new HelloMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getCid() const;
    virtual void setCid(int cid);
    virtual int getLevel() const;
    virtual void setLevel(int level);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HelloMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HelloMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HELLOMSG_M_H

