//
// Generated file, do not edit! Created by nedtool 5.6 from MinMsg.msg.
//

#ifndef __MINMSG_M_H
#define __MINMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
  #include "Event.h"
// }}

/**
 * Class generated from <tt>MinMsg.msg:5</tt> by nedtool.
 * <pre>
 * message MinMsg
 * {
 *     name = "min";
 *     kind = EventKind::MIN;
 *     int uid; //The ID of the message composer
 *     double weight;  // The weight of the link
 *     int minUid;     // The min UID of a link
 *     int maxUid;     // The max UID of a link
 * }
 * </pre>
 */
class MinMsg : public ::omnetpp::cMessage
{
  protected:
    int uid;
    double weight;
    int minUid;
    int maxUid;

  private:
    void copy(const MinMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MinMsg&);

  public:
    MinMsg(const char *name=nullptr, short kind=0);
    MinMsg(const MinMsg& other);
    virtual ~MinMsg();
    MinMsg& operator=(const MinMsg& other);
    virtual MinMsg *dup() const override {return new MinMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getUid() const;
    virtual void setUid(int uid);
    virtual double getWeight() const;
    virtual void setWeight(double weight);
    virtual int getMinUid() const;
    virtual void setMinUid(int minUid);
    virtual int getMaxUid() const;
    virtual void setMaxUid(int maxUid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MinMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MinMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MINMSG_M_H

