//
// Generated file, do not edit! Created by nedtool 5.6 from ReqMsg.msg.
//

#ifndef __REQMSG_M_H
#define __REQMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
  #include "Event.h"
// }}

/**
 * Class generated from <tt>ReqMsg.msg:5</tt> by nedtool.
 * <pre>
 * message ReqMsg
 * {
 *     name = "req";
 *     int contactPointId;  // The ID of the contact point
 *     int cid;             // The cluster ID
 *     int level;           // The cluster level
 * }
 * </pre>
 */
class ReqMsg : public ::omnetpp::cMessage
{
  protected:
    int contactPointId;
    int cid;
    int level;

  private:
    void copy(const ReqMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReqMsg&);

  public:
    ReqMsg(const char *name=nullptr, short kind=0);
    ReqMsg(const ReqMsg& other);
    virtual ~ReqMsg();
    ReqMsg& operator=(const ReqMsg& other);
    virtual ReqMsg *dup() const override {return new ReqMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getContactPointId() const;
    virtual void setContactPointId(int contactPointId);
    virtual int getCid() const;
    virtual void setCid(int cid);
    virtual int getLevel() const;
    virtual void setLevel(int level);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReqMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReqMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REQMSG_M_H

